FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY TrackingService/TrackingService.csproj TrackingService/
COPY TrackingService.DAL/TrackingService.DAL.csproj TrackingService.DAL/
COPY Logger/Logger.csproj Logger/
COPY StatusTracker.Api/StatusTracker.Api.csproj StatusTracker.Api/
RUN dotnet restore StatusTracker.Api/StatusTracker.Api.csproj
COPY . .
WORKDIR /src/StatusTracker.Api
RUN dotnet build StatusTracker.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish StatusTracker.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "StatusTracker.Api.dll"]